GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "john doe",
    "number": "555-5555"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "me",
    "number": "555-5555"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "few numbers",
    "number": "555-55"
}